# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78ed2ddeccea9c4e944f5dd8d739af9996d2dc64c02260e050fc9c147b6e99922fac2e923f47532db37adb072e3cec9fa56be142da5e7c69736f2a93fe09142

test:
  secret_key_base: 3433c957e290d998ac54dc8f714c85a1d37d708c9ba6446b8dc33d58797364de4e57a03c987f185f41d1e081c42efd6566bb9943b4fea5dc1fd6ff7c030f5a8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
